[project]
author = "Craig"
name = "mypackagefromtoml"
url = "https://my-arb-url"
version = "0.0.11"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project.scripts]
add = "craigmath.mathmain:add"
sub = "craigmath.mathmain:sub"
